"""IntegrationToken: Add webhook_primary_id

Revision ID: 5990ba2f0920
Revises: 37b999062857
Create Date: 2025-09-29 11:02:51.038244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector



# revision identifiers, used by Alembic.
revision: str = '5990ba2f0920'
down_revision: Union[str, Sequence[str], None] = '37b999062857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration_tokens', sa.Column('webhook_primary_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration_tokens', 'webhook_primary_id')
    # ### end Alembic commands ###
