"""add source_id to raw_entries

Revision ID: 8e81569715dd
Revises: 575932ee04ce
Create Date: 2025-07-28 17:43:48.665134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector



# revision identifiers, used by Alembic.
revision: str = '8e81569715dd'
down_revision: Union[str, Sequence[str], None] = '575932ee04ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_entries', sa.Column('source_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint('uq_user_source_source_id', 'raw_entries', ['user_id', 'source', 'source_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_source_source_id', 'raw_entries', type_='unique')
    op.drop_column('raw_entries', 'source_id')
    # ### end Alembic commands ###
