"""remove_webhook_tokens_table

Revision ID: aa16a57fab93
Revises: e9946f283b94
Create Date: 2025-10-07 12:59:08.645403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa16a57fab93'
down_revision: Union[str, Sequence[str], None] = 'e9946f283b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Remove webhook_tokens table - no longer needed for unified webhook approach.

    Verification tokens now stored in environment variables instead of per-user database records.
    The new unified webhook endpoint (/webhook/notion) routes based on bot_id from accessible_by array.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webhook_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('verification_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('webhook_tokens_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('webhook_tokens_pkey')),
    sa.UniqueConstraint('user_id', 'source', name=op.f('webhook_tokens_user_id_source_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
