"""support_multi_workspace_notion_integration

Revision ID: e9946f283b94
Revises: 5990ba2f0920
Create Date: 2025-10-07 12:13:06.928764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector



# revision identifiers, used by Alembic.
revision: str = 'e9946f283b94'
down_revision: Union[str, Sequence[str], None] = '5990ba2f0920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema to support multiple workspaces per user for Notion integration.

    Changes:
    - Drop old constraint: (user_id, integration_type) unique
    - Add new constraint: (user_id, integration_type, webhook_primary_id) unique
    - Add index on (integration_type, webhook_primary_id) for fast webhook routing

    This allows users to connect multiple Notion workspaces (e.g., Personal + Work),
    each with a unique bot_id stored in webhook_primary_id.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('integration_tokens_user_id_integration_type_key'), 'integration_tokens', type_='unique')
    op.create_index('idx_webhook_routing', 'integration_tokens', ['integration_type', 'webhook_primary_id'], unique=False)
    op.create_unique_constraint('integration_tokens_user_workspace_key', 'integration_tokens', ['user_id', 'integration_type', 'webhook_primary_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('integration_tokens_user_workspace_key', 'integration_tokens', type_='unique')
    op.drop_index('idx_webhook_routing', table_name='integration_tokens')
    op.create_unique_constraint(op.f('integration_tokens_user_id_integration_type_key'), 'integration_tokens', ['user_id', 'integration_type'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
